feat: pokedex api get pokemon list
NicoEnriquezFFuFm/pokedex-async-redux pull request #18
Opened 2023-03-20 08:51 UTC by NicoEnriquezFFuFm

- added future annotation next to void and async in main
- added freezed to pokemon.dart model
- added getPokemonlist function inside pokemon_api.dart to the list of pokemon
- added variable inside on main.dart to test if the api works

2023-03-20 08:59 UTC, NicoEnriquezFFuFm commented
![image](https://user-images.githubusercontent.com/128012634/226292148-6ac7f7f4-3039-4eb1-aa44-d9fdb999aa8d.png)

2023-03-21 01:04 UTC, shawn-ffufm commented on lib/api/handler/pokemon_api.dart
> +  // TODO: to be continued
do you still need this?

2023-03-21 01:04 UTC, shawn-ffufm requested changes
@NicoEnriquezFFuFm see minor feedback 🙂

2023-03-21 01:13 UTC, shawn-ffufm approved these changes

2023-03-21 07:38 UTC, shawn-ffufm approved these changes

2023-03-21 07:38 UTC, merged